"""Self-check for the /pixel-assets/<file> route (owner-requested
2026-09-16 -- sprites/backdrop for the Ultron tab's pixel companion,
generated by dev-tools/gen_pixel_assets.py). Same pattern and same real
things to get right as test_hero_assets_route.py's /three-pipeline check.

Run standalone from anywhere:
    python dev-tools/test_pixel_assets_route.py
"""
import os
import re
import sys
import tempfile

BACKEND_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "ultron-backend")
FAKE_PKGS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fake_pkgs")
sys.path.insert(0, FAKE_PKGS_DIR)
sys.path.insert(0, BACKEND_DIR)

os.environ["ULTRON_API_TOKEN"] = "admin-test-token"
os.environ["ULTRON_DB_PATH"] = os.path.join(tempfile.mkdtemp(), "test_ultron.db")
os.environ["ULTRON_DISABLE_MEMORY_TRENDS"] = "1"

import app  # noqa: E402


def demo():
    client = app.app.test_client()

    # Every sprite the room script asks for must exist and be served,
    # unauthenticated -- same reasoning as /three-pipeline. The per-agent
    # names are read out of the dashboard's own SUBAGENTS table, so adding an
    # agent there without generating its art fails here rather than showing
    # up as a missing desk.
    dashboard = open(os.path.join(BACKEND_DIR, "..", "ultron-dashboard.html"), encoding="utf-8").read()
    table = dashboard[dashboard.index("var SUBAGENTS = ["):dashboard.index("];", dashboard.index("var SUBAGENTS = ["))]
    colors = re.findall(r"color: '(\w+)'", table)
    assert len(colors) >= 17 and len(set(colors)) == len(colors), colors
    names = ["room_storey.png", "room_ground.png", "ultron_walk_a.png", "ultron_walk_b.png", "ultron_work.png",
             "desk_ultron_idle.png", "desk_ultron_active.png", "tube_red.png"]
    for c in colors:
        names += [f"agent_{c}.png", f"desk_{c}_idle.png", f"desk_{c}_active.png", f"tube_{c}.png"]
    for name in names:
        res = client.get("/pixel-assets/" + name)
        assert res.status_code == 200, (name, res.status_code)
        assert res.data[:8] == bytes([0x89]) + b"PNG" + bytes([13, 10, 26, 10]), name

    res = client.get("/pixel-assets/does-not-exist.png")
    assert res.status_code == 404, res.status_code

    # Path traversal must not escape pixel-assets/ (plain and percent-encoded).
    res = client.get("/pixel-assets/../ultron-backend/app.py")
    assert res.status_code in (403, 404), f"path traversal should be refused, got {res.status_code}"
    res = client.get("/pixel-assets/..%2f..%2fultron-backend%2fapp.py")
    assert res.status_code in (403, 404), f"encoded path traversal should be refused, got {res.status_code}"

    print("OK: /pixel-assets/<file> serves the real generated sprites/backdrop, "
          "404s for a missing file, and refuses path traversal (plain and percent-encoded).")


if __name__ == "__main__":
    demo()
