"""Self-check for the /pixel-assets/<file> route (owner-requested
2026-09-16 -- sprites/backdrop for the Ultron tab's pixel companion,
generated by dev-tools/gen_pixel_assets.py). Same pattern and same real
things to get right as test_hero_assets_route.py's /three-pipeline check.

Run standalone from anywhere:
    python dev-tools/test_pixel_assets_route.py
"""
import os
import sys
import tempfile

BACKEND_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "ultron-backend")
FAKE_PKGS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fake_pkgs")
sys.path.insert(0, FAKE_PKGS_DIR)
sys.path.insert(0, BACKEND_DIR)

os.environ["ULTRON_API_TOKEN"] = "admin-test-token"
os.environ["ULTRON_DB_PATH"] = os.path.join(tempfile.mkdtemp(), "test_ultron.db")
os.environ["ULTRON_DISABLE_MEMORY_TRENDS"] = "1"

import app  # noqa: E402


def demo():
    client = app.app.test_client()

    # Real generated assets the dashboard actually loads must be
    # reachable, unauthenticated -- same reasoning as /three-pipeline.
    for name in ("room_bg.png", "ultron_walk_a.png", "ultron_sit.png",
                 "agent_cyan_sit.png", "desk_ultron_active.png", "tube_red.png"):
        res = client.get("/pixel-assets/" + name)
        assert res.status_code == 200, (name, res.status_code)
        assert res.data[:8] == b"\x89PNG\r\n\x1a\n", (name, "doesn't start with the PNG magic bytes")

    # A file that doesn't exist 404s, not a 500 or a silent empty-body 200.
    res = client.get("/pixel-assets/does-not-exist.png")
    assert res.status_code == 404, res.status_code

    # Path traversal must not escape pixel-assets/ (plain and percent-encoded).
    res = client.get("/pixel-assets/../ultron-backend/app.py")
    assert res.status_code in (403, 404), f"path traversal should be refused, got {res.status_code}"
    res = client.get("/pixel-assets/..%2f..%2fultron-backend%2fapp.py")
    assert res.status_code in (403, 404), f"encoded path traversal should be refused, got {res.status_code}"

    print("OK: /pixel-assets/<file> serves the real generated sprites/backdrop, "
          "404s for a missing file, and refuses path traversal (plain and percent-encoded).")


if __name__ == "__main__":
    demo()
