"""Post-processing enrichment for graphify's graph.json -- adds what
KNOWLEDGE-GRAPH-GAP-SPEC.md (Module 2) found missing: per-node
timestamps, a real `tags` array + a standalone tag index, and a
public/private `visibility` flag that's genuinely enforced (private
node content is moved out of the plaintext graph entirely, encrypted
at rest, not just labeled). See GRAPH-SCHEMA-DESIGN.md for the full
design this implements and its known limits.

Deliberately NOT a fork of graphify's graph store: this reads
graphify-out/graph.json exactly as graphify wrote it and writes back
into the same file, adding fields to the same node dicts. Run this
after any `graphify update` / rebuild:

    python graph-schema/enrich_visibility.py

Idempotent -- safe to run repeatedly. date_created is preserved across
runs via .node_history.json; date_updated only moves when the node's
source file's mtime (from graphify's own manifest.json) actually
changed, not just because this script ran again.
"""
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from cryptography.fernet import Fernet

ROOT = Path(__file__).resolve().parent.parent
GRAPH_PATH = ROOT / "graphify-out" / "graph.json"
MANIFEST_PATH = ROOT / "graphify-out" / "manifest.json"
HISTORY_PATH = ROOT / "graph-schema" / ".node_history.json"
TAG_INDEX_PATH = ROOT / "graphify-out" / "tag-index.json"
PRIVATE_STORE_PATH = ROOT / "graphify-out" / "private-nodes.enc.json"
ENV_PATH = ROOT / ".env"
KEY_ENV_VAR = "ULTRON_GRAPH_ENCRYPTION_KEY"

# Roadmap's explicit hard-private categories (Module 4, step 14) plus
# what step 13 asks for generally: "default new/unclear node types to
# PRIVATE unless explicitly marked public-safe" -- so this list is
# deliberately broad, and the classifier defaults private on any doubt,
# not the reverse.
_PRIVATE_KEYWORDS = (
    "api key", "api_key", "apikey", "credential", "password", "secret",
    "token", "bearer", "auth token",
    "vpn", "wireguard", "tailscale", "network config", "firewall",
    "home lab", "raspberry pi", "pi-setup",
    "trading position", "account balance", "portfolio", "trade record",
    "financial", "realized gain", "tax lot", "fifo",
    "ssn", "passport", "beta spend", "spend cap",
)
_IP_RE = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")


def classify_visibility(node):
    # Sticky once private: a node already redacted by a prior run has had
    # its telltale content stripped from the plaintext graph by design,
    # so re-classifying from the stub alone would misread it as public
    # the moment the very keywords that made it private are gone. Once
    # private, it takes a human clearing the flag (not yet built -- see
    # GRAPH-SCHEMA-DESIGN.md's known limitations) to make it public again.
    if node.get("visibility") == "private":
        return "private"
    haystack = " ".join(
        str(node.get(k, "")) for k in ("label", "source_file", "community_name", "norm_label")
    ).lower()
    if _IP_RE.search(haystack):
        return "private"
    for kw in _PRIVATE_KEYWORDS:
        if kw in haystack:
            return "private"
    return "public"


def _slug(text):
    return re.sub(r"[^a-z0-9]+", "_", str(text).lower()).strip("_")


def derive_tags(node, visibility):
    tags = []
    if node.get("file_type"):
        tags.append(f"type:{node['file_type']}")
    if node.get("community_name"):
        tags.append(f"community:{_slug(node['community_name'])}")
    tags.append(f"visibility:{visibility}")
    return tags


def _load_json(path, default):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return default


def _file_mtime_iso(source_file, manifest):
    entry = manifest.get(source_file)
    if entry and entry.get("mtime"):
        return datetime.fromtimestamp(entry["mtime"], tz=timezone.utc).isoformat()
    return datetime.now(timezone.utc).isoformat()


def _get_or_create_key(env_path=ENV_PATH, private_store_path=PRIVATE_STORE_PATH, quiet=False):
    """Reuse ULTRON_GRAPH_ENCRYPTION_KEY from .env if present, else
    generate one and append it -- .env is already gitignored (see
    .gitignore), same pattern as every other secret this project holds.
    Losing this key means losing the ability to decrypt existing
    private-nodes.enc.json content -- there is no recovery path."""
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith(f"{KEY_ENV_VAR}="):
                return line.split("=", 1)[1].strip().encode("utf-8")
    key = Fernet.generate_key()
    with env_path.open("a", encoding="utf-8") as f:
        f.write("\n# Generated by graph-schema/enrich_visibility.py -- encrypts private\n")
        f.write("# knowledge-graph node content at rest. Back this up separately; if it's\n")
        f.write(f"# lost, {private_store_path.name} becomes permanently unreadable.\n")
        f.write(f"{KEY_ENV_VAR}={key.decode('utf-8')}\n")
    if not quiet:
        print(f"[enrich] generated a new encryption key and appended it to {env_path.name} "
              f"-- back it up, losing it means losing every private node's content.")
    return key


def enrich(graph_path=GRAPH_PATH, manifest_path=MANIFEST_PATH, history_path=HISTORY_PATH,
           tag_index_path=TAG_INDEX_PATH, private_store_path=PRIVATE_STORE_PATH, env_path=ENV_PATH):
    graph = json.loads(graph_path.read_text(encoding="utf-8"))
    manifest = _load_json(manifest_path, {})
    history = _load_json(history_path, {})
    private_store = _load_json(private_store_path, {})

    key = _get_or_create_key(env_path, private_store_path)
    fernet = Fernet(key)

    now = datetime.now(timezone.utc).isoformat()
    tag_index = {}
    private_count = 0

    for node in graph["nodes"]:
        node_id = node["id"]

        # A node already redacted by a prior run is missing exactly the
        # fields classification/tagging need (that's what redaction
        # means) -- recover the real content from the encrypted store
        # first so re-deriving tags/timestamps on a rerun works off real
        # data, not an empty stub.
        if node.get("visibility") == "private" and node_id in private_store:
            full = json.loads(fernet.decrypt(private_store[node_id].encode("ascii")))
        else:
            full = node

        visibility = classify_visibility(full)
        tags = derive_tags(full, visibility)

        source_file = full.get("source_file", "")
        updated = _file_mtime_iso(source_file, manifest) if source_file else now
        if node_id in history:
            created = history[node_id]["date_created"]
        else:
            created = updated
        history[node_id] = {"date_created": created, "date_updated": updated}

        full["category"] = full.get("file_type", "concept")
        full["tags"] = tags
        full["visibility"] = visibility
        full["date_created"] = created
        full["date_updated"] = updated

        for tag in tags:
            tag_index.setdefault(tag, []).append(node_id)

        if visibility == "private":
            private_count += 1
            # Full node content, encrypted, keyed by id -- never enters
            # graph.json or git. The public graph keeps only a redacted
            # stub so graph topology (edges, community structure) still
            # works without exposing the real label/source content.
            plaintext = json.dumps(full, ensure_ascii=False).encode("utf-8")
            private_store[node_id] = fernet.encrypt(plaintext).decode("ascii")
            # Capture before clear() -- when this is the first time this
            # node is classified private, `full is node`, so clearing
            # node would also wipe full out from under us.
            category, community = full["category"], full.get("community")
            node.clear()
            node.update({
                "id": node_id,
                "label": "[private]",
                "visibility": "private",
                "category": category,
                "community": community,
                "date_created": created,
                "date_updated": updated,
            })
        else:
            private_store.pop(node_id, None)
            if node is not full:
                node.clear()
                node.update(full)

    graph_path.write_text(json.dumps(graph, indent=2, ensure_ascii=False), encoding="utf-8")
    history_path.write_text(json.dumps(history, indent=2, ensure_ascii=False), encoding="utf-8")
    tag_index_path.write_text(json.dumps(tag_index, indent=2, ensure_ascii=False), encoding="utf-8")
    private_store_path.write_text(json.dumps(private_store, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"[enrich] {len(graph['nodes'])} nodes: {private_count} private (redacted + encrypted), "
          f"{len(graph['nodes']) - private_count} public. Tag index: {len(tag_index)} tags.")


def decrypt_private_node(node_id, key=None, private_store_path=PRIVATE_STORE_PATH):
    """Retrieval-time helper (for Module 8's read path later): returns
    the full original node dict for a private node id, or None if it
    isn't in the private store. Raises cryptography.fernet.InvalidToken
    if the key is wrong."""
    key = key or _get_or_create_key()
    store = _load_json(private_store_path, {})
    if node_id not in store:
        return None
    plaintext = Fernet(key).decrypt(store[node_id].encode("ascii"))
    return json.loads(plaintext)


if __name__ == "__main__":
    if not GRAPH_PATH.exists():
        print(f"[enrich] {GRAPH_PATH} not found -- run graphify first.", file=sys.stderr)
        sys.exit(1)
    enrich()
