"""Self-check for Module 8's read path.

Two kinds of proof:
1. Mechanism correctness against a small synthetic graph -- seed
   matching, one-hop expansion, the widen-on-sparse-match fallback, and
   the real bug this caught (a structural tag key like "visibility"
   matching every node, since every node has a visibility:X tag by
   construction).
2. "Accuracy hasn't dropped" (step 32) against the REAL graph, the only
   honest way to check this without a live LLM eval: hand-verified
   recall checks. For each sample query, a small set of node ids that
   MUST be in the result, chosen by inspecting the real graph -- not
   generated by the tool itself, since asserting a tool's output
   against ids it produced would prove nothing.

Run standalone from anywhere:
    python session-read/test_retrieve.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "ultron-backend"))
from retrieve_context import retrieve, format_for_context  # noqa: E402
from graph_schema_shared import _tag_words  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
GRAPH_PATH = ROOT / "graphify-out" / "graph.json"
TAG_INDEX_PATH = ROOT / "graphify-out" / "tag-index.json"


def demo_synthetic():
    graph = {
        "nodes": [
            {"id": "a", "label": "TTS streaming fix", "visibility": "public"},
            {"id": "b", "label": "fish audio client", "visibility": "public"},
            {"id": "c", "label": "unrelated trade ledger", "visibility": "public"},
            {"id": "d", "label": "another unrelated thing", "visibility": "private"},
        ],
        "links": [
            {"source": "a", "target": "b", "relation": "calls"},
            {"source": "c", "target": "d", "relation": "calls"},
        ],
    }
    tag_index = {
        "type:code": ["a", "b", "c", "d"],
        "visibility:public": ["a", "b", "c"],
        "visibility:private": ["d"],
        "topic:audio": ["b"],
    }

    # The real bug: "visibility" as a bare query word must NOT match via
    # the structural tag key -- only via a tag's actual value.
    assert "visibility" not in _tag_words("visibility:public"), _tag_words("visibility:public")
    assert "public" in _tag_words("visibility:public")

    result = retrieve("streaming audio", graph, tag_index, min_nodes=1)
    assert set(result["seed_ids"]) == {"a", "b"}, result["seed_ids"]
    assert result["neighbor_ids"] == [], result["neighbor_ids"]  # a<->b already both seeds

    result2 = retrieve("trade ledger", graph, tag_index, min_nodes=1)
    assert result2["seed_ids"] == ["c"], result2["seed_ids"]
    assert result2["neighbor_ids"] == ["d"], result2["neighbor_ids"]  # one-hop via c->d
    assert not result2["widened"]

    # Widen-on-sparse-match: min_nodes higher than what a tight match finds.
    result3 = retrieve("trade ledger", graph, tag_index, min_nodes=10)
    assert result3["widened"] is True

    text = format_for_context("trade ledger", result2, len(graph["nodes"]))
    assert "[seed]" in text and "[linked]" in text
    assert "2 of 4 total" in text, text

    print("OK: tag matching ignores structural tag keys (the real bug), seed matching, "
          "one-hop expansion, and widen-on-sparse-match all behave correctly.")


def demo_real_graph_recall():
    """Hand-verified: these node ids were chosen by inspecting the real
    graph directly, not by running the tool and copying its output."""
    graph = json.loads(GRAPH_PATH.read_text(encoding="utf-8"))
    tag_index = json.loads(TAG_INDEX_PATH.read_text(encoding="utf-8"))
    node_ids = {n["id"] for n in graph["nodes"]}

    expectations = {
        "TTS streaming fix": {"ultron_backend_app_fish_audio_tts", "dev_tools_test_tts_streaming"},
    }

    missing_from_graph = {i for ids in expectations.values() for i in ids} - node_ids
    if missing_from_graph:
        print(f"[test_retrieve] SKIP recall check: expected ids not found in the current graph "
              f"(node ids shift as the graph evolves) -- {missing_from_graph}")
        return

    for query, expected_ids in expectations.items():
        if not expected_ids:
            continue
        result = retrieve(query, graph, tag_index)
        got_ids = {n["id"] for n in result["nodes"]}
        missing = expected_ids - got_ids
        assert not missing, f"query {query!r} missed expected node(s) {missing} -- recall regression"

    print("OK: hand-verified recall check passed against the real graph (or skipped cleanly "
          "if expected node ids have since changed).")


if __name__ == "__main__":
    demo_synthetic()
    demo_real_graph_recall()
